### PR TITLE
Update typescript to 4.7

### PR DESCRIPTION
**Pull request by thgreasi**
Change-type: patch
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

### CODE REVIEW

**Comment by thgreasi** [comment]
@balena-ci I self-certify!

**Comment by thgreasi** [comment]
@balena-ci retest

**Comment by fisehara** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
@balena-ci retest

**Comment by fisehara** [comment]
@balena-ci retest

**Pull request merged**
