### PR TITLE
Run tests on UTC TZ

### PR DESCRIPTION
**Pull request by otaviojacobi**
Change-type: patch

### CODE REVIEW

**Comment by joshbwlng** [comment]
I'd recommend also setting `TZ: UTC` on the postgres service in `docker-compose.npm-test.yml` to make sure the test runner and db are in sync. Currently the postgres container defaults to UTC, but I'd like to make it explicit.

As was discussed internally, we should switch to using `timestamp with time zone` data for a proper fix, but I think we should still merge this PR.

**Comment by otaviojacobi** [comment]
@joshbwlng From https://www.postgresql.org/docs/8.3/libpq-envars.html
I believe the correct env var we should set for postgesql container is in fact `PGTZ` 

> PGTZ sets the default time zone. (Equivalent to SET timezone TO ....)

**Comment by joshbwlng** [comment]
@otaviojacobi From what I understand, `PGTZ` is for client sessions while `TZ` is affects the server-side system time zone. I tested setting `TZ=Asia/Tokyo` and `PGTZ=UTC` at the same time and the timestamps were wonky like before.

**Comment by otaviojacobi** [comment]
@joshbwlng  Oh I see, thanks! I tested locally with both set to UTC which wasn't very smart...
Should be fixed now

**Review by joshbwlng — APPROVED** [review]

**Pull request merged**
